entity_dict_CRO = {
    'Sime_Vrsaljko': ['Sime', 'Vrsaljko', 'Sime Vrsaljko'],
    'Domagoj_Vida': ['Domagoj', 'Vida', 'Domagoj Vida'],
    'Marcelo_Brozovic': ['Marcelo', 'Brozovic', 'Marcelo Brozovic'],
    'Dominik_Livakovic': ['Dominik', 'Livakovic', 'Dominik Livakovic'],
    'Tin_Jedvaj': ['Tin', 'Jedvaj', 'Tin Jedvaj'],
    'Mario_Mandzukic': ['Mario', 'Mandzukic', 'Mario Mandzukic'],
    'Marko_Pjaca': ['Marko', 'Pjaca', 'Marko Pjaca'],
    'Lovre_Kalinic': ['Lovre', 'Kalinic', 'Lovre Kalinic'],
    'Andrej_Kramaric': ['Andrej', 'Kramaric', 'Andrej Kramaric'],
    'Vedran_Corluka': ['Vedran', 'Corluka', 'Vedran Corluka'],
    'Nikola_Kalinic': ['Nikola', 'Kalinic', 'Nikola Kalinic'],
    'Josip_Pivaric': ['Josip', 'Pivaric', 'Josip Pivaric'],
    'Milan_Badelj': ['Milan', 'Badelj', 'Milan Badelj'],
    'Dejan_Lovren': ['Dejan', 'Lovren', 'Dejan Lovren'],
    'Ante_Rebic': ['Ante', 'Rebic', 'Ante Rebic'],
    'Ivan_Rakitic': ['Ivan', 'Rakitic', 'Ivan Rakitic'],
    'Luka_Modric': ['Luka', 'Modric', 'Luka Modric'],
    'Duje_Caleta-Car': ['Duje', 'Caleta-Car', 'Duje Caleta-Car'],
    'Ivan_Strinic': ['Ivan', 'Strinic', 'Ivan Strinic'],
    'Filip_Bradaric': ['Filip', 'Bradaric', 'Filip Bradaric'],
    'Danijel_Subasic': ['Danijel', 'Subasic', 'Danijel Subasic'],
    'Ivan_Perisic': ['Ivan', 'Perisic', 'Ivan Perisic'],
    'Mateo_Kovacic': ['Mateo', 'Kovacic', 'Mateo Kovacic'],
    'Dalic_Zlatko': ['Dalic', 'Zlatko', 'Dalic Zlatko'],
    'Croatia': ['Croatia', '#CRO', '#Croatia']
}

entity_dict_CRO_url = {
    'Sime_Vrsaljko': 'https://api.fifa.com/api/v1/picture/players/2018fwc/336485_sq-300_jpg?allowDefaultPicture=true',
    'Domagoj_Vida': 'https://api.fifa.com/api/v1/picture/players/2018fwc/299896_sq-300_jpg?allowDefaultPicture=true',
    'Marcelo_Brozovic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/380000_sq-300_jpg?allowDefaultPicture=true',
    'Dominik_Livakovic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/369029_sq-300_jpg?allowDefaultPicture=true',
    'Tin_Jedvaj': 'https://api.fifa.com/api/v1/picture/players/2018fwc/372987_sq-300_jpg?allowDefaultPicture=true',
    'Mario_Mandzukic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/375518_sq-300_jpg?allowDefaultPicture=true',
    'Marko_Pjaca': 'https://api.fifa.com/api/v1/picture/players/2018fwc/369057_sq-300_jpg?allowDefaultPicture=true',
    'Lovre_Kalinic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/376287_sq-300_jpg?allowDefaultPicture=true',
    'Andrej_Kramaric': 'https://api.fifa.com/api/v1/picture/players/2018fwc/336472_sq-300_jpg?allowDefaultPicture=true',
    'Vedran_Corluka': 'https://api.fifa.com/api/v1/picture/players/2018fwc/297373_sq-300_jpg?allowDefaultPicture=true',
    'Nikola_Kalinic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/297379_sq-300_jpg?allowDefaultPicture=true',
    'Josip_Pivaric': 'https://api.fifa.com/api/v1/picture/players/2018fwc/375261_sq-300_jpg?allowDefaultPicture=true',
    'Milan_Badelj': 'https://api.fifa.com/api/v1/picture/players/2018fwc/357991_sq-300_jpg?allowDefaultPicture=true',
    'Dejan_Lovren': 'https://api.fifa.com/api/v1/picture/players/2018fwc/312432_sq-300_jpg?allowDefaultPicture=true',
    'Ante_Rebic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/369058_sq-300_jpg?allowDefaultPicture=true',
    'Ivan_Rakitic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/296633_sq-300_jpg?allowDefaultPicture=true',
    'Luka_Modric': 'https://api.fifa.com/api/v1/picture/players/2018fwc/241559_sq-300_jpg?allowDefaultPicture=true',
    'Duje_Caleta-Car': 'https://api.fifa.com/api/v1/picture/players/2018fwc/372424_sq-300_jpg?allowDefaultPicture=true',
    'Ivan_Strinic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/357988_sq-300_jpg?allowDefaultPicture=true',
    'Filip_Bradaric': 'https://api.fifa.com/api/v1/picture/players/2018fwc/402149_sq-300_jpg?allowDefaultPicture=true',
    'Danijel_Subasic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/299887_sq-300_jpg?allowDefaultPicture=true',
    'Ivan_Perisic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/359381_sq-300_jpg?allowDefaultPicture=true',
    'Mateo_Kovacic': 'https://api.fifa.com/api/v1/picture/players/2018fwc/339987_sq-300_jpg?allowDefaultPicture=true',
    'Dalic_Zlatko': 'https://api.fifa.com/api/v1/picture/players/2018fwc/400769_sq-300_jpg?allowDefaultPicture=true',
    'Croatia': 'https://api.fifa.com/api/v1/picture/flags-fwc2018-4/cro'
}

entity_dict_ENG = {
    'Jamie_Vardy': ['Jamie', 'Vardy', 'Jamie Vardy'],
    'Danny_Rose': ['Danny', 'Rose', 'Danny Rose'],
    'Jesse__Lingard': ['Jesse', '', 'Lingard', 'Jesse  Lingard'],
    'Phil_Jones': ['Phil', 'Jones', 'Phil Jones'],
    'Harry_Kane': ['Harry', 'Kane', 'Harry Kane'],
    'Marcus_Rashford': ['Marcus', 'Rashford', 'Marcus Rashford'],
    'Kieran_Trippier': ['Kieran', 'Trippier', 'Kieran Trippier'],
    'Ruben_Loftus-Cheek': ['Ruben', 'Loftus-Cheek', 'Ruben Loftus-Cheek'],
    'Southgate_Gareth': ['Southgate', 'Gareth', 'Southgate Gareth'],
    'Jack_Butland': ['Jack', 'Butland', 'Jack Butland'],
    'Ashley__Young': ['Ashley', '', 'Young', 'Ashley  Young'],
    'Raheem_Sterling': ['Raheem', 'Sterling', 'Raheem Sterling'],
    'Jordan_Henderson': ['Jordan', 'Henderson', 'Jordan Henderson'],
    'Harry_Maguire': ['Harry', 'Maguire', 'Harry Maguire'],
    'John_Stones': ['John', 'Stones', 'John Stones'],
    'Nick_Pope': ['Nick', 'Pope', 'Nick Pope'],
    'Dele_Alli': ['Dele', 'Alli', 'Dele Alli'],
    'Trent_Alexander-Arnold': ['Trent', 'Alexander-Arnold', 'Trent Alexander-Arnold'],
    'Jordan_Pickford': ['Jordan', 'Pickford', 'Jordan Pickford'],
    'Kyle_Walker': ['Kyle', 'Walker', 'Kyle Walker'],
    'Eric__Dier': ['Eric', '', 'Dier', 'Eric  Dier'],
    'Fabian_Delph': ['Fabian', 'Delph', 'Fabian Delph'],
    'Gary_Cahill': ['Gary', 'Cahill', 'Gary Cahill'],
    'Danny_Welbeck': ['Danny', 'Welbeck', 'Danny Welbeck'],
    'England': ['England', '#ENG', '#England']
}

entity_dict_ENG_url = {
    'Jamie_Vardy': 'https://api.fifa.com/api/v1/picture/players/2018fwc/400820_sq-300_jpg?allowDefaultPicture=true',
    'Danny_Rose': 'https://api.fifa.com/api/v1/picture/players/2018fwc/274036_sq-300_jpg?allowDefaultPicture=true',
    'Jesse__Lingard': 'https://api.fifa.com/api/v1/picture/players/2018fwc/398743_sq-300_jpg?allowDefaultPicture=true',
    'Phil_Jones': 'https://api.fifa.com/api/v1/picture/players/2018fwc/358009_sq-300_jpg?allowDefaultPicture=true',
    'Harry_Kane': 'https://api.fifa.com/api/v1/picture/players/2018fwc/369419_sq-300_jpg?allowDefaultPicture=true',
    'Marcus_Rashford': 'https://api.fifa.com/api/v1/picture/players/2018fwc/401470_sq-300_jpg?allowDefaultPicture=true',
    'Kieran_Trippier': 'https://api.fifa.com/api/v1/picture/players/2018fwc/306504_sq-300_jpg?allowDefaultPicture=true',
    'Ruben_Loftus-Cheek': 'https://api.fifa.com/api/v1/picture/players/2018fwc/411303_sq-300_jpg?allowDefaultPicture=true',
    'Southgate_Gareth': 'https://api.fifa.com/api/v1/picture/players/2018fwc/155121_sq-300_jpg?allowDefaultPicture=true',
    'Jack_Butland': 'https://api.fifa.com/api/v1/picture/players/2018fwc/344536_sq-300_jpg?allowDefaultPicture=true',
    'Ashley__Young': 'https://api.fifa.com/api/v1/picture/players/2018fwc/299962_sq-300_jpg?allowDefaultPicture=true',
    'Raheem_Sterling': 'https://api.fifa.com/api/v1/picture/players/2018fwc/336043_sq-300_jpg?allowDefaultPicture=true',
    'Jordan_Henderson': 'https://api.fifa.com/api/v1/picture/players/2018fwc/356189_sq-300_jpg?allowDefaultPicture=true',
    'Harry_Maguire': 'https://api.fifa.com/api/v1/picture/players/2018fwc/407498_sq-300_jpg?allowDefaultPicture=true',
    'John_Stones': 'https://api.fifa.com/api/v1/picture/players/2018fwc/369434_sq-300_jpg?allowDefaultPicture=true',
    'Nick_Pope': 'https://api.fifa.com/api/v1/picture/players/2018fwc/411304_sq-300_jpg?allowDefaultPicture=true',
    'Dele_Alli': 'https://api.fifa.com/api/v1/picture/players/2018fwc/401298_sq-300_jpg?allowDefaultPicture=true',
    'Trent_Alexander-Arnold': 'https://api.fifa.com/api/v1/picture/players/2018fwc/390761_sq-300_jpg?allowDefaultPicture=true',
    'Jordan_Pickford': 'https://api.fifa.com/api/v1/picture/players/2018fwc/336022_sq-300_jpg?allowDefaultPicture=true',
    'Kyle_Walker': 'https://api.fifa.com/api/v1/picture/players/2018fwc/356750_sq-300_jpg?allowDefaultPicture=true',
    'Eric__Dier': 'https://api.fifa.com/api/v1/picture/players/2018fwc/369400_sq-300_jpg?allowDefaultPicture=true',
    'Fabian_Delph': 'https://api.fifa.com/api/v1/picture/players/2018fwc/306520_sq-300_jpg?allowDefaultPicture=true',
    'Gary_Cahill': 'https://api.fifa.com/api/v1/picture/players/2018fwc/305764_sq-300_jpg?allowDefaultPicture=true',
    'Danny_Welbeck': 'https://api.fifa.com/api/v1/picture/players/2018fwc/274034_sq-300_jpg?allowDefaultPicture=true',
    'England': 'https://api.fifa.com/api/v1/picture/flags-fwc2018-4/eng'
}

entity_dict_FRA = {
    'Nabil_Fekir': ['Nabil', 'Fekir', 'Nabil Fekir'], 
    'Ousmane_Dembele': ['Ousmane', 'Dembele', 'Ousmane Dembele'], 
    'Benjamin_Pavard': ['Benjamin', 'Pavard', 'Benjamin Pavard'], 
    'Benjamin_Mendy': ['Benjamin', 'Mendy', 'Benjamin Mendy'], 
    'Olivier_Giroud': ['Olivier', 'Giroud', 'Olivier Giroud'], 
    'Djibril_Sidibe': ['Djibril', 'Sidibe', 'DjibrilSidibe'], 
    'Blaise_Matuidi': ['Blaise', 'Matuidi', 'Blaise Matuidi'], 
    'Paul_Pogba': ['Paul', 'Pogba', 'Paul Pogba'], 
    'Ngolo_Kante': ['Ngolo', 'Kante', 'Ngolo Kante'], 
    'Antoine_Griezmann': ['Antoine', 'Griezmann', 'Antoine Griezmann'], 
    'Presnel_Kimpembe': ['Presnel', 'Kimpembe', 'Presnel Kimpembe'], 
    'Steven_Nzonzi': ['Steven', 'Nzonzi', 'Steven Nzonzi'], 
    'Lucas_Hernandez': ['Lucas', 'Hernandez', 'Lucas Hernandez'], 
    'Steve_Mandanda': ['Steve', 'Mandanda', 'Steve Mandanda'], 
    'Adil_Rami': ['Adil', 'Rami', 'Adil Rami'], 
    'Hugo_Lloris': ['Hugo', 'Lloris', 'Hugo Lloris'], 
    'Corentin_Tolisso': ['Corentin', 'Tolisso', 'Corentin Tolisso'], 
    'Deschamps_Didier': ['Deschamps', 'Didier', 'Deschamps Didier'], 
    'Florian_Thauvin': ['Florian', 'Thauvin', 'Florian Thauvin'], 
    'Thomas_Lemar': ['Thomas', 'Lemar', 'Thomas Lemar'], 
    'Samuel_Umtiti': ['Samuel', 'Umtiti', 'Samuel Umtiti'], 
    'Raphael_Varane': ['Raphael', 'Varane', 'Raphael Varane'], 
    'Alphonse_Areola': ['Alphonse', 'Areola', 'Alphonse Areola'], 
    'Kylian_Mbappe': ['Kylian', 'Mbappe', 'Kylian Mbappe'],
    'France': ['#FRA', '#France', 'France']
    }

entity_dict_BEL = {
    'Simon_Mignolet': ['Simon', 'Mignolet', 'Simon Mignolet'], 
    'Jan_Vertonghen': ['Jan', 'Vertonghen', 'Jan Vertonghen'], 
    'Adnan_Januzaj': ['Adnan', 'Januzaj', 'Adnan Januzaj'], 
    'Thomas_Vermaelen': ['Thomas', 'Vermaelen', 'Thomas Vermaelen'], 
    'Romelu_Lukak': ['Romel', 'Lukak', 'Romelu Lukak'], 
    'Leander_Dendoncker': ['Leander', 'Dendoncker', 'Leander Dendoncker'], 
    'Martinez_Roberto': ['Martinez', 'Roberto', 'Martinez Roberto'], 
    'Nacer_Chadli': ['Nacer', 'Chadli', 'Nacer Chadli'], 
    'Dedryck_Boyata': ['Dedryck', 'Boyata', 'Dedryck Boyata'], 
    'Yannick_Carrasco': ['Yannick', 'Carrasco', 'Yannick Carrasco'], 
    'Kevin_De_Bruyne': ['Kevin', 'De', 'Bruyne', 'Kevin De Bruyne'], 
    'Marouane_Fellaini': ['Marouane', 'Fellaini', 'Marouane Fellaini'], 
    'Vincent_Kompany': ['Vincent', 'Kompany', 'Vincent Kompany'], 
    'Thorgan_Hazard': ['Thorgan', 'Hazard', 'Thorgan Hazard'], 
    'Thibaut_Courtois': ['Thibaut', 'Courtois', 'Thibaut Courtois'], 
    'Michy_Batshuayi': ['Michy', 'Batshuayi', 'Michy Batshuayi'], 
    'Moussa_Dembele': ['Moussa', 'Dembele', 'Moussa Dembele'], 
    'Youri_Tielemans': ['Youri', 'Tielemans', 'Youri Tielemans'], 
    'Toby_Alderweireld': ['Toby', 'Alderweireld', 'Toby Alderweireld'], 
    'Thomas_Meunier': ['Thomas', 'Meunier', 'Thomas Meunier'], 
    'Axel_Witsel': ['Axel', 'Witsel', 'Axel Witsel'], 
    'Eden_Hazard': ['Eden', 'Hazard', 'Eden Hazard'], 
    'Koen_Casteels': ['Koen', 'Casteels', 'Koen Casteels'], 
    'Dries_Mertens': ['Dries', 'Mertens', 'Dries Mertens'],
    'Belgium': ['#BEL', '#Belgium', 'Belgium']
}


